# Generated by Django 2.1.4 on 2019-01-08 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999 9999 99'.", regex='^\\+?1?\\d{10}$')])),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
