# Generated by Django 2.1.4 on 2019-01-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0002_usersignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
    ]
