# Generated by Django 2.1.4 on 2019-01-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0003_auto_20190109_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Mobile Number'),
        ),
    ]
