# Generated by Django 2.1.4 on 2019-01-24 12:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0004_auto_20190109_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
