# Generated by Django 2.1.4 on 2019-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0006_auto_20190124_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
